export const articles={ko:[
{slug:"exam-overview",category:"시험 구조",title:"주택관리사보 1·2차 구조 한눈에 보기",description:"1차 3과목과 2차 2과목의 문항 형태·시간·합격 결정을 정확히 구분합니다.",sections:[["1차는 3과목 120문항입니다","회계원리, 공동주택시설개론, 민법을 과목당 40문항씩 풉니다. 1교시는 회계원리와 시설개론 100분, 2교시는 민법 50분입니다."],["2차는 객관식과 단답형이 섞입니다","주택관리관계법규와 공동주택관리실무를 과목별 객관식 24문항·주관식 단답형 16문항으로, 총 80문항 100분 동안 풉니다."],["1차와 2차의 합격 결정이 다릅니다","1차는 과목별 40점 이상이면서 평균 60점 이상이어야 합니다. 2차는 같은 기준을 충족한 사람 중 선발예정인원 범위에서 고득점자 순으로 결정됩니다."],["2026년 일정은 차수별로 나뉩니다","제29회 1차는 6월 27일, 2차는 9월 19일입니다. 접수와 발표 일정은 Q-Net 최신 공고를 확인하세요."]]},
{slug:"stage-plan",category:"전체 전략",title:"1차 기초와 2차 선발 경쟁을 함께 설계하기",description:"과락 방어를 넘어 2차 고득점 순위까지 고려한 과목별 계획을 만듭니다.",sections:[["1차는 세 과목 바닥을 먼저 지킵니다","전체 평균이 높아도 한 과목이 40점 아래면 합격할 수 없습니다. 회계·시설·민법을 별도 기록으로 관리합니다."],["2차는 60점만 목표로 멈추지 않습니다","선발예정인원 범위의 고득점자 순 결정이 있으므로 법규와 실무 모두 안정적인 득점을 목표로 합니다."],["차수별 회독을 연결합니다","민법의 권리관계는 관리 법규에, 시설개론의 구조·설비는 관리실무에 연결해 중복 학습을 줄입니다."],["실전은 교시 단위로 재현합니다","1차 100분·50분과 2차 100분을 실제 순서로 풀며 객관식 마킹과 단답형 작성 시간을 함께 점검합니다."]]},
{slug:"accounting",category:"1차 · 회계원리",title:"회계원리를 거래에서 재무제표까지 연결하기",description:"분개·결산·원가 흐름을 계산 순서와 검산 규칙으로 안정화합니다.",sections:[["거래의 두 방향을 먼저 찾습니다","무엇이 늘고 줄었는지, 자산·부채·자본·수익·비용 중 어디에 속하는지 판단한 뒤 차변과 대변을 정합니다."],["결산은 조정 전후를 분리합니다","발생·이연·감가상각과 충당 항목은 기간 귀속을 먼저 정하고 재무제표 영향을 추적합니다."],["관리회계는 공식을 구조로 이해합니다","원가행태, 손익분기와 의사결정 계산은 기호 암기보다 항목 간 관계와 단위를 확인합니다."],["계산 오답은 원인별로 나눕니다","분개 오류, 공식 선택, 부호, 단위와 단순 산술을 구분하면 같은 실수를 빠르게 줄일 수 있습니다."]]},
{slug:"facilities",category:"1차 · 시설개론",title:"공동주택시설개론을 구조와 설비 흐름으로 읽기",description:"건축구조와 급배수·전기·소방·승강기 설비를 점검 관점으로 묶습니다.",sections:[["구조는 하중의 길을 따라갑니다","기초에서 기둥·벽·보·슬래브로 이어지는 힘의 전달과 재료별 특성을 도식화합니다."],["설비는 공급과 배출을 함께 봅니다","급수·배수·환기·난방의 유입, 변환, 분배와 배출 과정을 한 흐름으로 정리합니다."],["안전설비는 목적과 작동을 연결합니다","소방, 전기, 가스와 승강기 설비의 감지·차단·피난 기능을 구성 요소와 함께 익힙니다."],["수치 기준은 대상과 조건을 붙입니다","치수·용량·간격을 외울 때 적용 시설, 예외와 기준 시점을 함께 기록합니다."]]},
{slug:"civil-law",category:"1차 · 민법",title:"민법을 권리관계와 시간순서로 정리하기",description:"법률행위·물권·채권을 당사자, 요건, 효과의 순서로 풀어냅니다.",sections:[["당사자와 청구를 먼저 표시합니다","누가 누구에게 어떤 권리를 주장하는지 적으면 긴 사례의 핵심 쟁점이 선명해집니다."],["성립·유효·대항을 구분합니다","계약의 성립, 효력 발생과 제3자에 대한 대항 요건을 섞지 않고 단계별로 판단합니다."],["시간순서를 그립니다","계약, 인도, 등기, 처분과 제3자 등장의 순서를 놓고 우선관계를 검토합니다."],["원칙과 예외의 조건을 읽습니다","선의·악의, 과실, 추인과 취소처럼 결론을 바꾸는 한정어를 문제에 직접 표시합니다."]]},
{slug:"housing-law",category:"2차 · 관계법규",title:"주택관리관계법규를 주체·절차·제재로 묶기",description:"공동주택 관리의 의사결정과 감독 절차를 법령별 역할로 구분합니다.",sections:[["법령별 목적부터 나눕니다","공동주택관리, 주택, 건축, 소방 등 각 법령이 다루는 대상과 행위를 먼저 구분합니다."],["관리 주체의 권한을 비교합니다","입주자대표회의, 관리주체, 관리사무소장, 사업주체와 행정기관의 의무를 표로 정리합니다."],["절차는 기산점과 순서를 붙입니다","신고·허가·공고·의결·보고에 필요한 기간과 시작 시점을 함께 기록합니다."],["위반과 제재를 대응시킵니다","금지행위가 행정처분, 과태료 또는 벌칙 중 무엇과 연결되는지 행위별로 비교합니다."]]},
{slug:"management-practice",category:"2차 · 관리실무",title:"공동주택관리실무를 현장 운영 흐름으로 익히기",description:"회계·계약·시설·안전·민원 업무를 관리 사이클로 연결합니다.",sections:[["업무를 연간 관리 사이클로 배치합니다","예산, 계약, 장기수선, 안전점검과 결산을 월간·분기·연간 일정에 놓습니다."],["회계는 증빙과 통제를 함께 봅니다","수입·지출 처리, 계정 분류, 결산과 공개 절차를 내부통제 목적과 연결합니다."],["시설은 예방과 대응을 구분합니다","정기점검·보수 계획과 고장·재난 발생 시 초동조치, 보고와 복구 순서를 나눕니다."],["단답형은 핵심어로 채점 대비합니다","질문이 요구하는 주체·요건·기한·행위를 짧고 정확한 법정 용어로 적는 연습을 반복합니다."]]},
{slug:"short-answer",category:"2차 · 주관식",title:"주관식 단답형 32문항을 득점원으로 만드는 법",description:"법정 용어와 숫자를 짧고 정확하게 인출하는 답안 루틴을 만듭니다.",sections:[["질문의 빈칸 유형을 분류합니다","용어, 주체, 기간, 금액, 비율과 절차 순서 중 무엇을 요구하는지 먼저 판별합니다."],["문장보다 채점 핵심어를 씁니다","장황한 설명 대신 법령상 정확한 명칭과 필요한 수치를 우선 적습니다."],["오답은 즉시 인출 카드로 바꿉니다","앞면에는 질문 조건, 뒷면에는 정답과 혼동 항목을 두고 짧은 간격으로 반복합니다."],["객관식과 시간을 나눕니다","2차 100분 안에서 객관식 검토와 단답형 작성·재확인 시간을 사전에 배분합니다."]]},
{slug:"law-update",category:"법령 최신화",title:"법령 개정과 시험 기준일을 관리하는 법",description:"기존 문제의 학습 가치를 보존하면서 바뀐 조문과 수치만 정확히 갱신합니다.",sections:[["연도별 시행공고를 출발점으로 삼습니다","시험에 적용되는 법령과 회계 기준의 기준 시점을 최신 공고에서 확인합니다."],["오답에 근거를 남깁니다","정답 문자만 저장하지 말고 법령명, 조문 주제, 기준일과 개정 여부를 기록합니다."],["변경 수치를 별도 표로 관리합니다","기간·금액·비율·인원과 처분 기준은 이전 값과 현재 값을 나란히 비교합니다."],["공식 원문을 우선합니다","앱이나 교재 설명이 최신 시행공고·법령과 충돌하면 공식 자료를 우선하고 수정 대상을 분리합니다."]]},
{slug:"twelve-week-plan",category:"학습 계획",title:"12주 1·2차 통합 학습 계획",description:"개념, 과목별 문제, 단답형 인출과 교시별 모의고사를 단계적으로 연결합니다.",sections:[["1~3주는 1차 기초를 세웁니다","회계 계산, 시설 구조와 민법 권리관계를 매일 순환하며 과목별 기본 점수를 만듭니다."],["4~7주는 2차를 확장합니다","관계법규의 주체·절차표와 관리실무의 운영 흐름을 만들고 단답형 인출을 시작합니다."],["8~10주는 과락과 선발 경쟁을 함께 봅니다","1차 40점 미만 위험을 닫고 2차는 평균 60점을 넘어 안정적인 고득점을 목표로 보강합니다."],["11~12주는 실제 교시를 재현합니다","1차 100분·50분, 2차 100분을 시간표대로 반복하고 마킹·단답형·휴식 루틴까지 고정합니다."]]}
],en:[
{slug:"exam-overview",category:"Format",title:"Korean Housing Manager exam at a glance",description:"Separate the three Stage 1 subjects from the mixed-format two-subject Stage 2.",sections:[["Stage 1 has 120 items","Accounting Principles, Apartment Facilities, and Civil Law each have 40 multiple-choice items."],["Stage 2 mixes two formats","Housing Management Law and Apartment Management Practice each have 24 multiple-choice and 16 short-answer items."],["The decisions differ by stage","Stage 1 uses a 40-per-subject floor and 60 average. Stage 2 applies those thresholds and then ranks qualifying scores within the planned selection number."],["The 2026 stages use separate dates","The 29th Stage 1 was June 27 and Stage 2 is September 19. Verify all dates on Q-Net."]]},
{slug:"stage-plan",category:"Overall strategy",title:"Plan Stage 1 foundations and Stage 2 ranking together",description:"Protect subject floors while aiming beyond the minimum in the competitive second stage.",sections:[["Protect all three Stage 1 floors","Track accounting, facilities and civil law separately so an overall average does not hide risk."],["Do not stop at 60 for Stage 2","Qualifiers are ranked within the announced selection number, so build margin in both subjects."],["Connect overlapping knowledge","Link civil-law rights to management law and facility systems to management practice."],["Reproduce each session","Run the 100- and 50-minute Stage 1 sessions and the 100-minute Stage 2 block."]]},
{slug:"accounting",category:"Stage 1 · Accounting",title:"Connect transactions, closing and statements",description:"Stabilise journal entries, adjustments and cost calculations with a repeatable sequence.",sections:[["Find both sides of a transaction","Classify what increases and decreases before assigning debit and credit."],["Separate pre- and post-adjustment values","Accruals, deferrals, depreciation and allowances depend on the correct period."],["Understand management-accounting structure","Check relationships and units before choosing a formula."],["Classify calculation errors","Separate journal, formula, sign, unit and arithmetic mistakes."]]},
{slug:"facilities",category:"Stage 1 · Facilities",title:"Read apartment facilities as structures and systems",description:"Link structural loads with water, electrical, fire, heating and lift systems.",sections:[["Follow the load path","Map how foundations, columns, walls, beams and slabs carry force."],["Pair supply with discharge","Trace input, conversion, distribution and removal in each building system."],["Connect safety purpose to operation","Study detection, shutdown and evacuation functions with their components."],["Attach numbers to conditions","Record each dimension, capacity or interval with its applicable facility and exception."]]},
{slug:"civil-law",category:"Stage 1 · Civil law",title:"Organise civil law by rights and timeline",description:"Resolve legal acts, property and obligations through parties, requirements and effects.",sections:[["Mark parties and claims","Identify who asserts which right against whom."],["Separate formation, validity and opposability","Evaluate each legal layer rather than mixing requirements."],["Draw the timeline","Place contract, delivery, registration, disposition and third parties in order."],["Read the conditions on exceptions","Good faith, negligence, ratification and cancellation can change the result."]]},
{slug:"housing-law",category:"Stage 2 · Law",title:"Group housing-management law by actor, process and sanction",description:"Distinguish the decision, management and supervision roles across statutes.",sections:[["Start with statutory purpose","Separate what each housing, building, fire or management statute governs."],["Compare actor powers","Map resident bodies, managers, office heads, developers and authorities."],["Attach deadlines to starting events","Learn the clock and sequence for reports, approvals, notices and votes."],["Match conduct to sanctions","Compare administrative measures, fines and criminal penalties."]]},
{slug:"management-practice",category:"Stage 2 · Practice",title:"Learn apartment management as an operating cycle",description:"Connect accounting, contracts, facilities, safety and resident service.",sections:[["Place work on an annual cycle","Schedule budgets, contracts, long-term repair, inspections and closing."],["Pair accounting with control","Connect evidence, account classification, closing and disclosure to internal controls."],["Separate prevention and response","Distinguish planned inspection from incident reporting and recovery."],["Answer short items with key terms","Use precise statutory actors, conditions, deadlines and actions."]]},
{slug:"short-answer",category:"Stage 2 · Short answer",title:"Turn 32 short-answer items into reliable points",description:"Build rapid recall for legal terms and numbers without wasting writing time.",sections:[["Classify the blank","Decide whether the prompt asks for a term, actor, period, amount, rate or sequence."],["Write scoring keywords first","Prefer the exact statutory name and required number over a long explanation."],["Convert errors to recall cards","Put the condition on one side and the answer plus confusion pair on the other."],["Budget the 100 minutes","Reserve distinct blocks for multiple choice, short answers and review."]]},
{slug:"law-update",category:"Legal updates",title:"Manage amendments and legal cutoff dates",description:"Preserve useful practice while updating only content that conflicts with current rules.",sections:[["Start with the annual notice","Identify the legal and accounting cutoff used for the exam year."],["Record the authority","Save the statute topic, cutoff and amendment status, not only an answer letter."],["Isolate changed numbers","Compare old and current periods, amounts, rates, people and sanctions."],["Prefer official text","Current notices and statutes control when secondary material conflicts."]]},
{slug:"twelve-week-plan",category:"Study plan",title:"A twelve-week Stage 1 and 2 plan",description:"Connect concepts, subject drills, short-answer recall and timed sessions.",sections:[["Weeks 1–3: Stage 1 foundation","Rotate accounting, facilities and civil-law fundamentals every day."],["Weeks 4–7: expand Stage 2","Build law process maps, management cycles and short-answer recall."],["Weeks 8–10: close floors and build margin","Remove Stage 1 subjects below 40 while pushing Stage 2 beyond the minimum."],["Weeks 11–12: reproduce sessions","Run 100, 50 and 100 minutes in order with marking and recovery routines."]]}
]};
